/* eslint-disable react/no-unknown-property */
/* eslint-disable react-hooks/exhaustive-deps */
import React from "react";
import Head from "next/head";

import Authentification from "@/components/Authentification";
import FetchAPI from "@/components/FetchAPI";
import FloatMedsos from "@/components/FloatMedsos";
import Firestore from "@/components/Firestore";
import Redux from "@/components/Redux";
import DynamicRoute from "@/components/DynamicRoute";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-green-500 min-h-[110vh]">
        <DynamicRoute />
        <Authentification />
        <Firestore />
        <FetchAPI />
        <Redux />
        <FloatMedsos />
      </main>
    </div>
  );
}
