import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import { useSelector, useDispatch } from "react-redux";
import { increment, decrement, addBy } from "../store/counter-slice";

export default function Home() {
  const count = useSelector((state) => state.counter);
  const dispatch = useDispatch();

  const [isActive, setIsActive] = useState(false);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-green-500">
        <h1>This is an example to testing my redux program</h1>
        <p>result increment = {count}</p>
        <button
          onClick={() => {
            dispatch(increment());
          }}
        >
          increment
        </button>
        <br />
        <button
          onClick={() => {
            dispatch(decrement());
          }}
        >
          decrement
        </button>
        <br />
        <button
          onClick={() => {
            dispatch(addBy(10));
          }}
        >
          decrement 10
        </button>
        {/* fixed button */}
        <div
          className={`flex flex-row-reverse fixed right-8 bottom-5 transition-all duration-500 items-center overflow-hidden ${
            isActive ? "-translate-y-36" : ""
          }`}
        >
          <div className={`opacity-0 transition-all duration-500 ${isActive ? "opacity-100" : ""}`}>
            <Image src="/whatsapp.svg" width={100} height={100} alt="whatsapp" />
          </div>
          <div
            className={`relative bottom-2 rounded-xl py-2 px-4 transition-all duration-300 delay-200 bg-white  ${
              isActive ? "translate-x-0" : "-translate-x-40"
            }`}
          >
            <p className="">Hubungi Kami</p>
          </div>
        </div>
        <div
          className={`fixed right-8 bottom-5 flex flex-row-reverse transition-all duration-500 items-center overflow-hidden ${
            isActive ? "translate-y-[-72px] " : ""
          }`}
        >
          <div className={`opacity-0 transition-all duration-500 ${isActive ? "opacity-100" : ""}`}>
            <Image src="/news.svg" width={100} height={100} alt="news" className="" />
          </div>
          <div
            className={`relative bottom-2 rounded-xl py-2 px-4 transition-all duration-300 delay-200 bg-white -z-10 ${
              isActive ? "translate-x-0" : "-translate-x-40"
            }`}
          >
            <p className="items-center bg-white">Berlangganan</p>
          </div>
        </div>
        <div></div>
        <div
          className={`fixed right-8 bottom-5 transition-all duration-300 ${
            isActive ? "" : "opacity-0"
          }`}
        >
          <Image src="/close.svg" width={100} height={100} alt="close" className="" />
        </div>
        <div
          onClick={() => {
            setIsActive(!isActive);
          }}
          className={`fixed right-5 bottom-5 transition-all duration-300 ${
            isActive ? "opacity-0" : ""
          }`}
        >
          <div></div>
          <Image
            src="/whatsapp-news.svg"
            width={130}
            height={130}
            alt="whatsapp-news"
            className=""
          />
        </div>

        {/* batas fixed button */}
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
        <h1> This is a title text</h1>
      </main>
    </div>
  );
}
